version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependabot:pypi"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependabot:npm"
