version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3-bullseye
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    network_mode: service:db
    environment:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
    command: sleep infinity

  node:
    image: node:18-bullseye-slim
    restart: unless-stopped
    volumes:
      - ..:/workspace:cached
    network_mode: service:db
    working_dir: /workspace
    command:
      - bash
      - -c
      - |
        yarn
        yarn dev --host

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
