name: Deploy

on:
  push:
    tags:
      - "^20[0-9]+.[0-9]+$"
    branches:
      - main
  workflow_dispatch:

concurrency: production

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  # https://github.com/marketplace/actions/sentry-release#create-a-sentry-internal-integration
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: "the-westervelt-company"
  SENTRY_PROJECT: "django_project"

jobs:
  bumpver:
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.bumpver.outputs.current_version }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install bumpver
        run: |
          python -m pip install --upgrade pip
          python -m pip install bumpver

      - name: Configure git to push
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "Automated Publisher"

      - name: Bump Version
        id: bumpver
        run: |
          bumpver update
          eval $(bumpver show --env)
          echo "{current_version}=$CURRENT_VERSION" >> $GITHUB_OUTPUT

      - name: Push Release Build to GitHub
        run: |
          git push

  deploy:
    runs-on: ubuntu-latest
    needs: bumpver
    environment: production
    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only

  sentry:
    runs-on: ubuntu-latest
    needs: bumpver
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create Sentry release
        uses: getsentry/action-release@v1.4.1
        with:
          environment: production
          version: ${{ needs.bumpver.outputs.current_version }}
